emily_crud_article:
    resource: "@EmilyCRUDBundle/Controller/ArticleController.php"
    type:     annotation

emily_crud:
    resource: "@EmilyCRUDBundle/Resources/config/routing.yml"
    prefix:   /CRUD

emily_twig:
    resource: "@EmilyTwigBundle/Resources/config/routing.yml"
    prefix:   /EmilyTwig

emily_racine:
    resource: "@EmilyRacineBundle/Resources/config/routing.yml"
    prefix:   /

